spring:
  application:
    name: eureka


server:
  port: 7900

eureka:
  instance:
    hostname: eureka-7900
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/

#  server: # Eureka 配置优化点
#    enable-self-preservation: false #自我保护
#    renewal-percent-threshold: 0.85 # 自我保护的阈值
#    eviction-interval-timer-in-ms: 1000 # 剔除服务的时间间隔
#    use-read-only-response-cache: false # eureka的三级缓存，关闭从readOnly读注册表
#    response-cache-update-interval-ms: 1000 # readWrite 和 readOnly 同步的时间间隔

#
#---
#spring:
#  config:
#    activate:
#      on-profile: 7900
#server:
#  port: 7900
#eureka:
#  instance:
#    hostname: eureka-7900
#
#---
#spring:
#  config:
#    activate:
#      on-profile: 7901
#server:
#  port: 7901
#eureka:
#  instance:
#    hostname: eureka-7901
#
#---
#spring:
#  config:
#    activate:
#      on-profile: 7902
#server:
#  port: 7902
#eureka:
#  instance:
#    hostname: eureka-7902
